# Раздел 2

### Задание 2.1

In [1]:
import numpy as np 
a = np.array([[2.3, 5.1, 4.7],  [3.5, 6.7, 1.5], [8.4, 3.1, 9.2]]) 
b = np.array([[4.3, 8.1, 6.1],  [3.7, 6.2, 1.5],  [2.4, 5.7, 4.7]])
print('сумма',a+b)
print('разн',a-b)
print('умнижение',a*b)
print('деление',a/b)

сумма [[ 6.6 13.2 10.8]
 [ 7.2 12.9  3. ]
 [10.8  8.8 13.9]]
разн [[-2.  -3.  -1.4]
 [-0.2  0.5  0. ]
 [ 6.  -2.6  4.5]]
умнижение [[ 9.89 41.31 28.67]
 [12.95 41.54  2.25]
 [20.16 17.67 43.24]]
деление [[0.53488372 0.62962963 0.7704918 ]
 [0.94594595 1.08064516 1.        ]
 [3.5        0.54385965 1.95744681]]
